name: tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
          
      - name: Install dependencies
        uses: php-actions/composer@v6
        
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-html coverage-report
